function OAS_RICH(position) {
if (position == 'Bottom2') {
document.write ('<!--JavaScript Tag // Tag for network 1001: Komli Media // Website: Miniclips DB // Page: Miniclip Contextual page // Placement: 728x90 (2936562) // created at: Dec 16, 2010 8:27:11 AM-->\n');
document.write ('<script>\n');
document.write ('  var komliAdKeywordsAdtech = ');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('  if(adKeywordsAdtech) {\n');
document.write ('  	komliAdKeywordsAdtech = adKeywordsAdtech;\n');
document.write ('  }\n');
document.write ('</script>\n');
document.write ('\n');
document.write ('<script language="javascript"><!--\n');
document.write ('document.write(');
document.write ("'");
document.write ('<scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt language="javascript1.1" src="http://adserver.adtech.de/addyn/3.0/1001/3029729/0/225/ADTECH;loc=100;target=_blank;key=');
document.write ("'");
document.write ('+komliAdKeywordsAdtech+');
document.write ("'");
document.write (';grp=[group];misc=');
document.write ("'");
document.write ('+new Date().getTime()+');
document.write ("'");
document.write (';rdclick="></scri');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('pt>');
document.write ("'");
document.write (');\n');
document.write ('//-->\n');
document.write ('</script><noscript><a href="http://adserver.adtech.de/adlink/3.0/1001/3029729/0/225/ADTECH;loc=300;key=key1+key2+key3+key4;grp=[group];rdclick=" target="_blank"><img src="http://adserver.adtech.de/adserv/3.0/1001/3029729/0/225/ADTECH;loc=300;key=key1+key2+key3+key4;grp=[group]" border="0" width="728" height="90"></a></noscript>\n');
document.write ('<!-- End of JavaScript Tag -->');
}
if (position == 'Middle') {
document.write ('<!--JavaScript Tag // Tag for network 1001: Komli Media // Website: Miniclips DB // Page: Miniclip Contextual page // Placement: 300x250 (2936566) // created at: Dec 16, 2010 8:23:50 AM-->\n');
document.write ('<script>\n');
document.write ('  var komliAdKeywordsAdtech = ');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('  if(adKeywordsAdtech) {\n');
document.write ('  	komliAdKeywordsAdtech = adKeywordsAdtech;\n');
document.write ('  }\n');
document.write ('</script>\n');
document.write ('<script language="javascript"><!--\n');
document.write ('document.write(');
document.write ("'");
document.write ('<scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt language="javascript1.1" src="http://adserver.adtech.de/addyn/3.0/1001/3029728/0/170/ADTECH;loc=100;target=_blank;key=');
document.write ("'");
document.write ('+komliAdKeywordsAdtech+');
document.write ("'");
document.write (';grp=[group];misc=');
document.write ("'");
document.write ('+new Date().getTime()+');
document.write ("'");
document.write (';rdclick="></scri');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('pt>');
document.write ("'");
document.write (');\n');
document.write ('//-->\n');
document.write ('</script><noscript><a href="http://adserver.adtech.de/adlink/3.0/1001/3029728/0/170/ADTECH;loc=300;key=key1+key2+key3+key4;grp=[group];rdclick=" target="_blank"><img src="http://adserver.adtech.de/adserv/3.0/1001/3029728/0/170/ADTECH;loc=300;key=key1+key2+key3+key4;grp=[group]" border="0" width="300" height="250"></a></noscript>\n');
document.write ('<!-- End of JavaScript Tag -->');
}
}
