(function(){
var h=void 0,n=!0,q=null,r=!1;var s=function(){},t=function(a){return"function"==typeof a},w=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},aa=function(a,b){if(Array.prototype.indexOf)return a.indexOf(b);for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1},ca=function(a,b){for(var c=new ba,d=0;d<a.length;d++)c.set(a[d],n);for(d=0;d<b.length;d++)if(c.get(b[d]))return n;return r},da=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},ea=function(a){return Math.round(Number(a))||0},ba=function(){this.prefix=
"gtm.";this.i={}};ba.prototype.set=function(a,b){this.i[this.prefix+a]=b};ba.prototype.get=function(a){return this.i[this.prefix+a]};var fa=function(a){try{return a[""](a)}catch(b){}return r};var x=window,y=document,z=function(a,b,c){return("http:"==x.location.protocol?b:a)+c},ga=function(a){var b=y.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},A=function(a,b,c){var d=y.createElement("script");d.type="text/javascript";d.async=n;d.src=a;b&&(d.onload=d.onreadystatechange=function(){if(!d.readyState||"loaded"==d.readyState||"complete"==d.readyState)d.onload=s,d.onreadystatechange=s,b()});c&&(d.onerror=c);ga(d)},ha=function(a,b){var c=y.createElement("iframe");c.height=
"0";c.width="0";c.style.display="none";c.style.visibility="hidden";ga(c);b&&(c.onload=c.onreadystatechange=function(){if(!c.readyState||"loaded"==c.readyState||"complete"==c.readyState)c.onload=s,c.onreadystatechange=s,b()});c.src=a},B=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=q;b&&b()};d.onerror=function(){d.onerror=q;c&&c()};d.src=a},D=function(a,b,c){a.addEventListener?a.addEventListener(b,c,r):a.attachEvent&&a.attachEvent("on"+b,c)},ia=r,ja=[],F=function(a){if((!a||!("readystatechange"==
a.type&&"interactive"!=y.readyState&&"complete"!=y.readyState))&&!ia){ia=n;for(var b=0;b<ja.length;b++)ja[b]()}},ka=0,la=function(){if(!ia&&140>ka){ka++;try{y.documentElement.doScroll("left"),F()}catch(a){x.setTimeout(la,50)}}},na=r,oa=[],pa=function(){if(!na){na=n;for(var a=0;a<oa.length;a++)oa[a]()}};var G=new ba,qa=s,H=[],ra=r,sa=r,ta=r,va=function(){for(;!ra&&0<H.length;){ra=n;var a=H.shift(),b=h;for(b in a)a.hasOwnProperty(b)&&G.set(b,a[b]);a.event&&("gtm.dom"==a.event&&(sa=n),"gtm.load"==a.event&&(ta=n),qa(a.event));ra=r}};var wa=q;
var xa=y.createElement("a"),ya=function(a){var b=x.location,c=b.hash?b.href.replace(b.hash,""):b.href,d=G.get("gtm.url");d&&(xa.href=c=String(d),b=xa);
return c},_u=ya;_u.b="u";var _eq=function(a){return String(a[""])==String(a[""])};_eq.b="eq";var Ka,O;
var I=function(a,b){return function(){}},N=function(a){return function(){}},J=function(a,b){
return""};var pb=function(){this.d=[]};pb.prototype.set=function(a,b){this.d.push([a,b]);return this};pb.prototype.e=function(){for(var a={},b=0;b<this.d.length;b++)a[T(this.d[b][0])]=T(this.d[b][1]);return a};
var rb=function(a){this.index=a;this.e=function(){return fa(qb[a])}},_M=function(a){return new rb(a)},sb=function(a){this.e=function(){for(var b=[],c=0;c<a.length;c++)b.push(T(V[a[c]]));return b.join("")}},_T=function(a){return new sb(arguments)},tb=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return n;return r}this.e=
function(){if(a[0]instanceof rb&&b(8)&&b(16))return'google_tag_manager["GTM-J54R"].macro('+a[0].index+")";for(var c=String(T(a[0])),d=1;d<a.length;d++)c=S[a[d]](c);return c}},_E=function(a,b){return new tb(arguments)},T=function(a){var b=a;if(a instanceof rb||a instanceof pb||a instanceof sb||a instanceof tb)return a.e();if(w(a))for(var b=[],c=0;c<a.length;c++)b[c]=T(a[c]);else if(a&&"object"==typeof a){var b={},d;for(d in a)a.hasOwnProperty(d)&&(b[d]=T(a[d]))}return b},ub=function(a,b){var c=b[a],
d=c;if(c instanceof rb||c instanceof tb||c instanceof sb)d=c;else if(w(c))for(var d=[],e=0;e<c.length;e++)d[e]=ub(c[e],b);else if("object"==typeof c){var d=new pb,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],ub(c[f],b))}return d},X=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=V[e[1]]);if(1==a)for(var f=vb(e[0]),e=c[d]={},g=0;g<W;g++)f[g]&&(e[wb[g][0]]=wb[g][1]);if(2==a)for(g=0;4>g;g++)e[g]=vb(e[g]);}return c},vb=function(a){for(var b=[],c=0;c<W;c++)b[c]=1<<c%6&"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".indexOf(a&&a.charAt(Math.floor(c/6))||"A")?1:0;return b};for(var W=0,V,Ab=[],Bb=[],Cb=0;Cb<Ab.length;Cb++)Bb[Cb]=ub(Cb,Ab);V=Bb;var wb=X(0,""),qb=X(1,""),Db=X(1,""),Z=X(1,""),Eb=X(2,"");var Hb=function(){var a=[];return function(b){if(a[b]===h){var c=Db[b]&&T(Db[b]);a[b]=[c&&fa(c),c]}return a[b]}},Ib=function(){var a=G.get("tagTypeBlacklist");if(w(a)){for(var b=[],c=0;c<a.length;c++)b.push(String(a[c]));return b}return[]},Jb=qa=function(a){wa=a;for(var d=vb(),e=vb(),f=Hb(),c=0;c<Eb.length;c++){var g=Eb[c],k;a:{for(var l=g,p=f,m=0;m<W;m++)if(l[0][m]&&!p(m)[0]||
l[2][m]&&p(m)[0]){k=r;break a}k=n}if(k)for(var C=g,v=d,L=e,K=0;K<W;K++)v[K]=v[K]||C[1][K],L[K]=L[K]||C[3][K];}var ua=[];for(var hb=Ib(),E=0;E<W;E++)if(d[E]&&!e[E]){var ib=Z[E][""];if(0>aa(hb,ib.b)&&!ca(hb,ib.c||[])){ua[E]=T(Z[E]);}else{}}for(var lb=Ib(),M=0;M<W;M++)if(d[M]&&!e[M]&&0>aa(lb,Z[M][""].b)&&!ca(lb,
Z[M][""].c||[])){fa(ua[M])}wa=q};var $={set:function(a,b){G.set(a,b)},event:function(a){Jb(a)},macro:function(a){return qb[a]&&fa(T(qb[a]))},f:{push:function(a){for(var b=arguments,c=0;c<b.length;c++)try{if(t(b[c][0]))b[c][0]();else $[b[c][0]].apply($,[].slice.call(b[c],1))}catch(d){}}},j:function(){var a=x["gtm"];if(a){var b=a.a;w(b)&&$.f.push.apply($.f,b);a.a=$.f;ja.push(function(){$.event("gtm.dom")});oa.push(function(){$.event("gtm.load")})}},k:function(){var a=x.google_tag_manager;a||(a=x.google_tag_manager={});a["GTM-J54R"]||
(a["GTM-J54R"]=$)}};$.k();$.j();(function(){var a=x["dataLayer"];if(a){var b=a.push;a.push=function(){var c=[].slice.call(arguments,0);b.apply(a,c);H.push.apply(H,c);va()};H.push.apply(H,a.slice(0));va();ja.push(function(){sa||a.push({event:"gtm.dom"})});oa.push(function(){ta||a.push({event:"gtm.load"})})}})();
if("interactive"==y.readyState||"complete"==y.readyState)F();else{D(y,"DOMContentLoaded",F);D(y,"readystatechange",F);if(y.createEventObject&&y.documentElement.doScroll){var Kb=n;try{Kb=!x.frameElement}catch(Lb){}Kb&&la()}D(x,"load",F)}"complete"===y.readyState?pa():D(x,"load",pa);var _vs="res_ts:1355928976575000,srv_cl:43242586,ds:live,cv:1";
})()
