#!/bin/sh
XGETTEXT_OPTIONS="--keyword=_ -keyword=N_ --default-domain=captcha --no-location"

# Allows controlling language option
# (gettext v.0.10.40 = -C, gettext 0.11+ = -L php).
if [ $SM_OLD_GETTEXT ] ; then
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -C";
else
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -L php";
fi

xgettext ${XGETTEXT_OPTIONS} *.php backends/b2evo/*.php backends/captcha_php/*.php backends/csi/*.php backends/freecap/*.php backends/hec/*.php backends/hn_captcha/*.php backends/meezerk/*.php backends/quickcaptcha/*.php backends/quickform/*.php backends/recaptcha/*.php backends/textcapnum/*.php backends/textcaptcha/*.php backends/watercap/*.php --output=captcha.pot
